import { Meet } from "./schema";

// FilAm meets data - major meets to potentially attend
export const filamMeets: Meet[] = [
  {
    id: 9999,
    name: "Moorpark Open",
    date: "2025-04-04",
    location: "Moorpark, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/235789/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9998,
    name: "Triton Invite",
    date: "2025-04-04",
    location: "San Diego, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.directathletics.com/meets/45672/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9997,
    name: "Brutus Hamilton Invite",
    date: "2025-04-05",
    location: "Berkeley, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/236112/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9996,
    name: "Chico Invitational",
    date: "2025-04-11",
    location: "Chico, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.directathletics.com/meets/45891/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9995,
    name: "Pomona-Pitzer Invitational",
    date: "2025-04-12",
    location: "Claremont, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/236445/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9994,
    name: "Chabot Finale",
    date: "2025-04-12",
    location: "Hayward, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.directathletics.com/meets/46012/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9993,
    name: "Bryan Clay Invitational",
    date: "2025-04-16",
    location: "Azusa, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/236778/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9992,
    name: "Cal State LA Invitational",
    date: "2025-04-16",
    location: "Los Angeles, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.directathletics.com/meets/46234/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9991,
    name: "Gary Shaw Meet (Hartnell College)",
    date: "2025-04-18",
    location: "Salinas, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/237001/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9990,
    name: "Johnny Mathis Invite",
    date: "2025-04-18",
    location: "San Francisco, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.directathletics.com/meets/46445/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9989,
    name: "Mt. SAC Relays",
    date: "2025-04-18",
    location: "Walnut, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: "https://www.athletic.net/TrackAndField/meet/237112/info",
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9988,
    name: "Singapore Open",
    date: "2025-04-24",
    location: "Singapore",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9987,
    name: "Payton Jordan Invitational",
    date: "2025-04-25",
    location: "Palo Alto, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9986,
    name: "Philippine National Championships",
    date: "2025-05-01",
    location: "New Clark City, Philippines",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9985,
    name: "PATAFA Pole Vault Challenge",
    date: "2025-05-06",
    location: "Imus, Cavite, Philippines",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9984,
    name: "HPU Last Chance",
    date: "2025-05-18",
    location: "High Point, NC",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9983,
    name: "Track Fest",
    date: "2025-05-24",
    location: "Los Angeles, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9982,
    name: "Asian Championships",
    date: "2025-05-27",
    location: "Korea",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9981,
    name: "Cal State San Marcos Summer Nights #5",
    date: "2025-05-28",
    location: "San Marcos, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9980,
    name: "Track Carnival",
    date: "2025-05-31",
    location: "Cleveland, TN",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9979,
    name: "Golden West Invite",
    date: "2025-06-07",
    location: "Rancho Cordova, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9978,
    name: "Jim Bush Invite (Open)",
    date: "2025-06-07",
    location: "Claremont, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9977,
    name: "Pole Vault in the Plaza",
    date: "2025-06-07",
    location: "Naples, FL",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9976,
    name: "Taiwan Open",
    date: "2025-06-07",
    location: "Taipei City, Taiwan",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9975,
    name: "Last Chance Sprint Series",
    date: "2025-06-13",
    location: "Sherman Oaks, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9974,
    name: "Busan PV Championships",
    date: "2025-06-13",
    location: "Busan, Korea",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9973,
    name: "EAP Malta International",
    date: "2025-06-14",
    location: "Malta",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9972,
    name: "Royal City Inferno",
    date: "2025-06-18",
    location: "Guelph, Canada",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9971,
    name: "Adidas Outdoor Nationals",
    date: "2025-06-20",
    location: "Greensboro, NC",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9970,
    name: "Thailand Open",
    date: "2025-06-22",
    location: "Thailand",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9969,
    name: "Bob Vigars Classic",
    date: "2025-06-22",
    location: "London, Canada",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9968,
    name: "University of Toronto Meet #4",
    date: "2025-06-24",
    location: "Toronto, Canada",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9967,
    name: "Jack Brow Meet",
    date: "2025-06-27",
    location: "Kelowna, Canada",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9966,
    name: "DC Vault",
    date: "2025-06-28",
    location: "Washington, DC",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9965,
    name: "Street Vault",
    date: "2025-06-28",
    location: "Santa Clarita, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9964,
    name: "MVA HP Invite",
    date: "2025-06-29",
    location: "Chula Vista, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9963,
    name: "LA Throws Cup",
    date: "2025-07-11",
    location: "Wilmington, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9962,
    name: "Vulcan Vault",
    date: "2025-07-12",
    location: "Homewood, AL",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9961,
    name: "MVA HP Invite",
    date: "2025-07-12",
    location: "Chula Vista, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9960,
    name: "Edmonton Invite",
    date: "2025-07-13",
    location: "Edmonton, Canada",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9959,
    name: "Gran Series",
    date: "2025-07-19",
    location: "Sherman Oaks, CA",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9958,
    name: "Dauphin Street Vault",
    date: "2025-07-19",
    location: "Mobile, AL",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9957,
    name: "Silk Road Continental Tour",
    date: "2025-08-16",
    location: "Tashkent, Uzbekistan",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9956,
    name: "Asian Throwing Championships",
    date: "2025-08-21",
    location: "Mokpo, Korea",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9955,
    name: "World Athletics Championships",
    date: "2025-09-13",
    location: "Tokyo, Japan",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  },
  {
    id: 9954,
    name: "Southeast Asian Games",
    date: "2025-12-11",
    location: "Bangkok, Thailand",
    description: null,
    heightCleared: null,
    poleUsed: null,
    deepestTakeoff: null,
    place: null,
    link: null,
    driveTime: null,
    registrationStatus: "not registered",
    createdAt: new Date()
  }
];